<?php

function sfschool_help( ) {
    switch ($section) { 
    case 'admin/modules#description': 
        return t('Implements hooks for CiviCRM to customize the SFSchool site');
    default :
        return;
    } 
}

function _sfschool_initialize( ) {
    $template = CRM_Core_Smarty::singleton( );

    $sfschoolDir = 
        dirname( __FILE__ ) . DIRECTORY_SEPARATOR .
        '..'                . DIRECTORY_SEPARATOR .
        '..'                . DIRECTORY_SEPARATOR .
        'templates';

    if ( is_array( $template->template_dir ) ) {
        $template->template_dir = array( $sfschoolDir ) + $template->template_dir;                            
    } else {
        $template->template_dir = array( $sfschoolDir, $template->template_dir );
    }

}

function sfschool_civicrm_pageRun( &$page ) {
    if ( $page->getVar( '_name' ) == 'CRM_Profile_Page_Dynamic' ) {
        $gid = $page->getVar( '_gid' );
        if ( $gid == 3 ) {
            return _sfschool_civicrm_pageRun_Profile_Page_Dynamic_3( $page, $gid );
        }
        if ( $gid == 4 ) {
            return _sfschool_civicrm_pageRun_Profile_Page_Dynamic_4( $page, $gid );
        }
        
    }
}

function _sfschool_civicrm_pageRun_Profile_Page_Dynamic_3( &$page, $gid ) {
    $parentID = $page->getVar( '_id' );
    $values = array( );

    require_once 'Utils/Query.php';
    sfschool_Utils_Query::checkSubType( $parentID, array( 'Parent', 'Staff' ) );

    require_once 'Utils/Relationship.php';
    sfschool_Utils_Relationship::getChildren( $parentID,
                                              $values,
                                              true );

    $childrenIDs = array_keys( $values );

    require_once 'Utils/Conference.php';
    sfschool_Utils_Conference::getValues( $childrenIDs, $values, false, $parentID );

    require_once 'Utils/ExtendedCare.php';
    sfschool_Utils_ExtendedCare::getValues( $childrenIDs, $values, $parentID );

    $page->assign( 'childrenInfo', $values );
}



function _sfschool_civicrm_pageRun_Profile_Page_Dynamic_4( &$page, $gid ) {
    $childID = $page->getVar( '_id' );

    require_once 'Utils/Query.php';
    sfschool_Utils_Query::checkSubType( $childID, 'Student' );

    $values = array( );
    $values[$childID] =
        array('name'    => CRM_Core_DAO::getFieldValue( 'CRM_Contact_DAO_Contact',
                                                        $childID,
                                                        'display_name' ),
              'grade'   => sfschool_Utils_Query::getGrade( $childID ),
              'parents' => array( ) );

    require_once 'Utils/Relationship.php';
    sfschool_Utils_Relationship::getParents( $childID,
                                             $values[$childID]['parents'],
                                             false );

    require_once 'Utils/Conference.php';
    sfschool_Utils_Conference::getValues( $childID, $values );

    require_once 'Utils/ExtendedCare.php';
    sfschool_Utils_ExtendedCare::getValues( $childID, $values );

    $page->assign( 'childInfo', $values[$childID] );
}

function sfschool_civicrm_buildForm( $formName, &$form ) {
    if ( $formName == 'CRM_Profile_Form_Edit' ) {
        $gid = $form->getVar( '_gid' );
        if ( $gid == 4 ) {
            return _sfschool_civicrm_buildForm_CRM_Profile_Form_Edit_4( $formName, $form, $gid );
        }
    }
}

function sfschool_civicrm_postProcess( $class, &$form ) {
    if ( is_a( $form, 'CRM_Profile_Form_Edit' ) ) {
        $gid = $form->getVar( '_gid' );
        if ( $gid == 4 ) {
            sfschool_civicrm_postProcess_CRM_Profile_Form_Edit_4( $class, $form, $gid );
            return;
        }
    }
}

function _sfschool_civicrm_buildForm_CRM_Profile_Form_Edit_4( $formName, &$form, $gid ) {
    // freeze first name, last name and grade
    $elementList = array( 'first_name', 'last_name', 'custom_2' );
    $form->freeze( $elementList );

    $childID   = $form->getVar( '_id' );

    require_once 'Utils/Conference.php';
    sfschool_Utils_Conference::buildForm( $form, $childID );

    require_once 'Utils/ExtendedCare.php';
    sfschool_Utils_ExtendedCare::buildForm( $form, $childID );
}


function sfschool_civicrm_postProcess_CRM_Profile_Form_Edit_4( $class, &$form, $gid ) {
    require_once 'Utils/Conference.php';
    sfschool_Utils_Conference::postProcess( $class, $form, $gid );

    require_once 'Utils/ExtendedCare.php';
    sfschool_Utils_ExtendedCare::postProcess( $class, $form, $gid );
}

function sfschool_civicrm_tabs( &$tabs, $contactID ) {
    require_once 'Utils/Query.php';
    $subType = sfschool_Utils_Query::getSubType( $contactID );

    // if subType is not student then hide the extended care tab
    if ( $subType == 'Student' ) {
        return;
    }

    foreach ( $tabs as $tabID => $tabValue ) {
        if ( $tabValue['title'] == 'Extended Care' ) {
            unset( $tabs[$tabID] );
            break;
        }
    }
}
