<?php

function _sfschool_initialize( ) {
    static $_initialized = false;

    if ( $_initialized ) {
        return;
    }

    $_initialized = true;

    // set the timezone
    date_default_timezone_set('America/Los_Angeles');
}

function sfschool_help( $path, $arg ) {
    switch ( $path ) { 
    case 'admin/modules#description': 
        return t('Conference signups, extended care activities and signups, online directories of the schools and grades, reports, relationship maintenance ..');
    default :
        return;
    } 
}

function sfschool_civicrm_config( &$config ) {
    $template =& CRM_Core_Smarty::singleton( );

    $sfschoolRoot = 
        dirname( __FILE__ ) . DIRECTORY_SEPARATOR .
        '..'                . DIRECTORY_SEPARATOR .
        '..'                . DIRECTORY_SEPARATOR;

    $sfschoolDir = $sfschoolRoot . 'templates';

    if ( is_array( $template->template_dir ) ) {
        $template->template_dir = array( $sfschoolDir ) + $template->template_dir;                            
    } else {
        $template->template_dir = array( $sfschoolDir, $template->template_dir );
    }

    // also fix php include path
    $include_path = $sfschoolRoot . PATH_SEPARATOR . get_include_path( );
    set_include_path( $include_path );
}

function sfschool_civicrm_pageRun( &$page ) {
    _sfschool_initialize( );

    $name = $page->getVar( '_name' );
    if ( $name == 'CRM_Profile_Page_Dynamic' ) {
        $gid = $page->getVar( '_gid' );
        switch ( $gid ) {
        case 3:
            return _sfschool_civicrm_pageRun_Profile_Page_Dynamic_3( $page, $gid );
        case 4:
            return _sfschool_civicrm_pageRun_Profile_Page_Dynamic_4( $page, $gid );
        }
    } else if ( $name == 'CRM_Contact_Page_View_CustomData' ) {
        if ( $page->getVar( '_groupId' ) != 2 ) {
            return;
        }

        // get the details from smarty
        $smarty  =& CRM_Core_Smarty::singleton( );
        $details =& $smarty->get_template_vars( 'viewCustomData' );
        
        require_once 'SFS/Utils/ExtendedCare.php';
         SFS_Utils_ExtendedCare::sortDetails( $details );

         // CRM_Core_Error::debug( 'POST', $details );
        $smarty->assign_by_ref( 'viewCustomData', $details );
    }

}

function _sfschool_civicrm_pageRun_Profile_Page_Dynamic_3( &$page, $gid ) {
    $parentID = $page->getVar( '_id' );
    $values = array( );

    require_once 'SFS/Utils/Query.php';
    SFS_Utils_Query::checkSubType( $parentID, array( 'Parent', 'Staff' ) );

    require_once 'SFS/Utils/Relationship.php';
    SFS_Utils_Relationship::getChildren( $parentID,
                                         $values,
                                         true );

    $childrenIDs = array_keys( $values );

    require_once 'SFS/Utils/Conference.php';
    SFS_Utils_Conference::getValues( $childrenIDs, $values, false, $parentID );

    require_once 'SFS/Utils/ExtendedCare.php';
    SFS_Utils_ExtendedCare::getValues( $childrenIDs, $values, $parentID );

    $page->assign( 'childrenInfo', $values );

    $subType = SFS_Utils_Query::getSubType( $parentID );
    if ( $subType == 'Staff' ) {
        $ptcValues = array( );
        SFS_Utils_Conference::getPTCValuesOccupied( $parentID, $ptcValues );

        $page->assign( 'ptcValues', $ptcValues );
    }

}

function _sfschool_civicrm_pageRun_Profile_Page_Dynamic_4( &$page, $gid ) {
    $childID = $page->getVar( '_id' );

    $term =  CRM_Utils_Request::retrieve( 'term', 'String',
                                          $page, false, null );
        
    require_once 'SFS/Utils/Query.php';
    SFS_Utils_Query::checkSubType( $childID, 'Student' );

    $values = array( );
    $values[$childID] =
        array('name'    => CRM_Core_DAO::getFieldValue( 'CRM_Contact_DAO_Contact',
                                                        $childID,
                                                        'display_name' ),
              'grade'   => SFS_Utils_Query::getGrade( $childID ),
              'parents' => array( ) );

    require_once 'SFS/Utils/Relationship.php';
    SFS_Utils_Relationship::getParents( $childID,
                                        $values[$childID]['parents'],
                                        false );

    require_once 'SFS/Utils/Conference.php';
    SFS_Utils_Conference::getValues( $childID, $values );

    require_once 'SFS/Utils/ExtendedCare.php';
    SFS_Utils_ExtendedCare::getValues( $childID, $values, null, $term );

    $page->assign( 'childInfo', $values[$childID] );
}

function sfschool_civicrm_buildForm( $formName, &$form ) {
    _sfschool_initialize( );

    if ( $formName == 'CRM_Profile_Form_Edit' ) {
        $gid = $form->getVar( '_gid' );
        switch ( $gid ) {
        case 3:
            return _sfschool_civicrm_buildForm_CRM_Profile_Form_Edit_3( $formName, $form, $gid );
        case 4:
            return _sfschool_civicrm_buildForm_CRM_Profile_Form_Edit_4( $formName, $form, $gid );
        }
    }
}

function sfschool_civicrm_validate( $formName, &$fields, &$files, &$form ) {
    if ( $formName == 'CRM_Profile_Form_Edit' ) {
        $gid = $form->getVar( '_gid' );
        if ( $gid = 3 ) {
            require_once 'SFS/Utils/Conference.php';
            return SFS_Utils_Conference::validatePTCForm( $form, $fields );
        }
    }
    return null;
}
	
function sfschool_civicrm_postProcess( $class, &$form ) {
    _sfschool_initialize( );

    if ( is_a( $form, 'CRM_Profile_Form_Edit' ) ) {
        $gid = $form->getVar( '_gid' );
        switch ( $gid ) {
        case 3:
            return sfschool_civicrm_postProcess_CRM_Profile_Form_Edit_3( $class, $form, $gid );
        case 4:
            return sfschool_civicrm_postProcess_CRM_Profile_Form_Edit_4( $class, $form, $gid );
        }
    }
}

function _sfschool_civicrm_buildForm_CRM_Profile_Form_Edit_3( $formName, &$form, $gid ) {
    $staffID   = $form->getVar( '_id' );

    // freeze first name, last name and grade
    $elementList = array( 'first_name', 'last_name', 'email-Primary', 'phone-Primary' );
    $form->freeze( $elementList );

    require_once 'SFS/Utils/Conference.php';
    SFS_Utils_Conference::buildPTCForm( $form, $staffID );
}

function _sfschool_civicrm_buildForm_CRM_Profile_Form_Edit_4( $formName, &$form, $gid ) {
    // freeze first name, last name and grade
    $elementList = array( 'first_name', 'last_name', 'custom_2' );
    $form->freeze( $elementList );

    $childID   = $form->getVar( '_id' );

    require_once 'SFS/Utils/Conference.php';
    SFS_Utils_Conference::buildForm( $form, $childID );

    $term =  CRM_Utils_Request::retrieve( 'term', 'String',
                                          $form, false, null );
        
    require_once 'SFS/Utils/ExtendedCare.php';
    SFS_Utils_ExtendedCare::buildForm( $form, $childID, $term );
}


function sfschool_civicrm_postProcess_CRM_Profile_Form_Edit_3( $class, &$form, $gid ) {
    $staffID   = $form->getVar( '_id' );

    require_once 'SFS/Utils/Conference.php';
    SFS_Utils_Conference::postProcessPTC( $form, $staffID );
}


function sfschool_civicrm_postProcess_CRM_Profile_Form_Edit_4( $class, &$form, $gid ) {
    require_once 'SFS/Utils/Conference.php';
    SFS_Utils_Conference::postProcess( $class, $form, $gid );

    $term =  CRM_Utils_Request::retrieve( 'term', 'String',
                                          $form, false, null );
        
    require_once 'SFS/Utils/ExtendedCare.php';
    SFS_Utils_ExtendedCare::postProcess( $class, $form, $gid, $term );
}

function sfschool_civicrm_tabs( &$tabs, $contactID ) {
    _sfschool_initialize( );

    require_once 'SFS/Utils/Query.php';
    $subType = SFS_Utils_Query::getSubType( $contactID );

    // if subType is not student then hide the extended care tab
    if ( $subType == 'Student' ) {
        return;
    }

    foreach ( $tabs as $tabID => $tabValue ) {
        if ( $tabValue['title'] == 'Extended Care' ||
             $tabValue['title'] == 'Extended Care Signout' ) {
            unset( $tabs[$tabID] );
        }
    }
}

function sfschool_civicrm_xmlMenu( &$files ) {
    $files[] =
        dirname( __FILE__ ) . DIRECTORY_SEPARATOR .
        '..'                . DIRECTORY_SEPARATOR .
        '..'                . DIRECTORY_SEPARATOR .
        'SFS'               . DIRECTORY_SEPARATOR .
        'xml'               . DIRECTORY_SEPARATOR .
        'Menu'              . DIRECTORY_SEPARATOR .
        'sfschool.xml';
}

function sfschool_user( $op, &$edit, &$account, $category = null ) {
    return;
    switch ( $op ) {
    case 'login':
        _sfschool_initialize( );
        
        // get the contact id and then the subtype
        require_once 'api/v2/UFGroup.php';
        $cid     = civicrm_uf_match_id_get( $account->uid );
        
        require_once 'SFS/Utils/Query.php';
        $subType = SFS_Utils_Query::getSubType( $cid );
        if ( $subType == 'Parent' ) {
            CRM_Utils_System::redirect( CRM_Utils_System::url( 'civicrm/profile/view',
                                                               'reset=1&gid=3' ) );
        }
    }
}
